# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Pascal-S-Complier

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Pascal-S-Complier

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Pascal-S-Complier/CMakeFiles /root/Pascal-S-Complier/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Pascal-S-Complier/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pascal_S_Complier

# Build rule for target.
Pascal_S_Complier: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Pascal_S_Complier
.PHONY : Pascal_S_Complier

# fast build rule for target.
Pascal_S_Complier/fast:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/build
.PHONY : Pascal_S_Complier/fast

# target to build an object file
parser/IdTable.o:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdTable.o
.PHONY : parser/IdTable.o

# target to preprocess a source file
parser/IdTable.i:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdTable.i
.PHONY : parser/IdTable.i

# target to generate assembly for a file
parser/IdTable.s:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdTable.s
.PHONY : parser/IdTable.s

# target to build an object file
parser/IdType.o:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdType.o
.PHONY : parser/IdType.o

# target to preprocess a source file
parser/IdType.i:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdType.i
.PHONY : parser/IdType.i

# target to generate assembly for a file
parser/IdType.s:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/IdType.s
.PHONY : parser/IdType.s

# target to build an object file
parser/debug.o:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/debug.o
.PHONY : parser/debug.o

# target to preprocess a source file
parser/debug.i:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/debug.i
.PHONY : parser/debug.i

# target to generate assembly for a file
parser/debug.s:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/debug.s
.PHONY : parser/debug.s

# target to build an object file
parser/parser.tab.o:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/parser.tab.o
.PHONY : parser/parser.tab.o

# target to preprocess a source file
parser/parser.tab.i:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/parser.tab.i
.PHONY : parser/parser.tab.i

# target to generate assembly for a file
parser/parser.tab.s:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/parser/parser.tab.s
.PHONY : parser/parser.tab.s

# target to build an object file
scanner/lex.yy.o:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/scanner/lex.yy.o
.PHONY : scanner/lex.yy.o

# target to preprocess a source file
scanner/lex.yy.i:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/scanner/lex.yy.i
.PHONY : scanner/lex.yy.i

# target to generate assembly for a file
scanner/lex.yy.s:
	$(MAKE) -f CMakeFiles/Pascal_S_Complier.dir/build.make CMakeFiles/Pascal_S_Complier.dir/scanner/lex.yy.s
.PHONY : scanner/lex.yy.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Pascal_S_Complier"
	@echo "... edit_cache"
	@echo "... parser/IdTable.o"
	@echo "... parser/IdTable.i"
	@echo "... parser/IdTable.s"
	@echo "... parser/IdType.o"
	@echo "... parser/IdType.i"
	@echo "... parser/IdType.s"
	@echo "... parser/debug.o"
	@echo "... parser/debug.i"
	@echo "... parser/debug.s"
	@echo "... parser/parser.tab.o"
	@echo "... parser/parser.tab.i"
	@echo "... parser/parser.tab.s"
	@echo "... scanner/lex.yy.o"
	@echo "... scanner/lex.yy.i"
	@echo "... scanner/lex.yy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

